# Generated by Django 6.0 on 2025-12-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('anio_lanzamiento', models.PositiveIntegerField()),
                ('plataforma', models.CharField(choices=[('PS3', 'PS3'), ('PS4', 'PS4'), ('PS5', 'PS5')], max_length=10)),
                ('formato', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=10)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
