# Generated by Django 6.0 on 2025-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], default='nuevo', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], max_length=10),
        ),
    ]
