# Generated by Django 6.0 on 2025-12-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producto_estado_alter_producto_formato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AlterField(
            model_name='producto',
            name='anio_lanzamiento',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='producto',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='store.genero'),
        ),
    ]
