# Generated by Django 6.0 on 2025-12-12 02:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_genero_remove_producto_genero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del género'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='anio_lanzamiento',
            field=models.DateField(help_text='Fecha aproximada de lanzamiento del juego.', verbose_name='Año de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve para el cliente.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], max_length=10, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='generos',
            field=models.ManyToManyField(blank=True, help_text='Puedes seleccionar uno o varios géneros.', to='store.genero', verbose_name='Géneros'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del juego'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plataforma',
            field=models.CharField(choices=[('PS3', 'PS3'), ('PS4', 'PS4'), ('PS5', 'PS5'), ('XBOX', 'Xbox'), ('SWITCH', 'Nintendo Switch'), ('PC', 'PC')], max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible (0 a 100.000).', validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta en CLP (entre 1.000 y 100.000.000).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000.00')), django.core.validators.MaxValueValidator(Decimal('100000000.00'))], verbose_name='Precio'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('nombre', 'plataforma', 'formato', 'estado'), name='unique_producto_por_plataforma_formato_estado'),
        ),
    ]
