# Generated by Django 6.0 on 2025-12-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_genero_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='plataforma',
            field=models.CharField(choices=[('PS3', 'PS3'), ('PS4', 'PS4'), ('PS5', 'PS5')], max_length=10, verbose_name='Plataforma'),
        ),
    ]
